# "feature" is the smallest logical grouping of test/test suites. Each feature maps roughly to a
# PM project but can be split up further if needed. This list can be trivially divided up as needed
# if it gets too large to fit into one file.
# Tests for features are defined in Python and can be arbitrarily
features:
- name: txns
  desription: |
    mechanisms of distributed transactions
- name: jsCore
  description: |
    deprecated definition "core" MongoDB features. New projects should not be added to this.

# "Modules" is a level of abstraction above "features" and map roughly to Server teams. modules have a many-to-many
# relationship with features.
modules:
- name: sharding
  features:
  - txns
  - jsCore
- name: replication
  features:
  - txns
- service-arch
- execution
- storage-engine
- security
- query-execution
- realm
- dummy-new-team
